### ISSUE TITLE
Work with Physijs

### ISSUE THREAD

**Issue by terflogag** [jeromeetienne/threex.spaceships#3]
I'm trying to work threex.spaceships with Physijs to detect collision with skybox. But it seem to be not compatible.
Have you any idea or solution ? 

Thank you for this awesome library.

**Comment by jeromeetienne** [comment]
this is only providing model. it seems more a physics problem, hello @chandlerprall :)

**Comment by chandlerprall** [comment]
@terflogag can you show an example of code you're trying to use? Also, for new projects I recommend starting off with [Physijs v2](https://github.com/chandlerprall/Physijs/tree/2.0) - it's not feature complete but it runs a lot better.

**Comment by terflogag** [comment]
Hello, 

I'm trying to detect collision between my skybox and my spaceship (which are in space environment). 
There is my code : 

```
// create a scene
scene = new Physijs.Scene;
scene.setGravity(new THREE.Vector3( 0, 0, 0 ));
```
My skybox are also made with physijs.
But I don't understand how to make my spaceship object with physijs (and not only with mesh around the spaceship).
Actually my spaceship are setup with this code : 
```
THREEx.SpaceShips.loadSpaceFighter03(function(object3d){
    this.player.addEventListener('collision', function(object) {
        console.log("collision");
      });

    scene.add(object3d);
  })
```
But the player are not made with Physijs and can't detect collision.. 

Thank's for your help :-)

**Comment by chandlerprall** [comment]
@terflogag There is no default support in Physijs for the loaders; you'll have to extract the geometry & materials from the loader's result (`object3d`) and create a new Physijs object from that.
